#!/usr/bin/env bash
# memory-persist.sh — Stop hook: auto-persist session learnings to .platform/memory/
#
# Input:  JSON on stdin (Claude Code Stop hook payload).
#         Shape: {"session_id":"...","stop_hook_active":true,...}
# Output: Nothing to stdout. Appends to .platform/memory/log.md and writes
#         .platform/memory/session-YYYYMMDD.md per turn.
#
# Fail-open: exit 0 unconditionally — never blocks a session.
#
# Opt-in:    NOT wired by `ab install-hooks`. Add manually to .claude/settings.json
#            under "Stop" — see ACTIVATE.md "Memory persistence hook" section.

set -uo pipefail

[[ -d ".platform" ]] || exit 0

INPUT="$(cat 2>/dev/null || true)"
[[ -n "$INPUT" ]] || exit 0

_json_field() {
  printf '%s' "$INPUT" | grep -o "\"${1}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" \
    | head -1 | grep -o '"[^"]*"$' | tr -d '"' 2>/dev/null || true
}

TODAY="$(date -u +%Y-%m-%d 2>/dev/null || true)"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || true)"
SESSION_ID="$(_json_field "session_id")"
[[ -n "$SESSION_ID" ]] || SESSION_ID="unknown-$(date +%s)"

# Files changed this session (from events.jsonl)
CHANGED_FILES=""
EVENTS_LOG=".platform/events.jsonl"
if [[ -f "$EVENTS_LOG" ]]; then
  CHANGED_FILES="$(grep "\"${SESSION_ID}\"" "$EVENTS_LOG" 2>/dev/null \
    | grep -o '"file":"[^"]*"' | grep -o '"[^"]*"$' | tr -d '"' | sort -u || true)"
fi

# Active stream (from BRIEF.md)
STREAM_SLUG=""
if [[ -f ".platform/work/BRIEF.md" ]]; then
  STREAM_SLUG="$(grep -o 'work/[^`]*\.md' ".platform/work/BRIEF.md" 2>/dev/null \
    | head -1 | sed 's|work/||; s|\.md||' || true)"
fi

# ── log.md breadcrumb ────────────────────────────────────────────────────────

LOG=".platform/memory/log.md"
mkdir -p ".platform/memory" 2>/dev/null || exit 0

FILE_COUNT="$(printf '%s\n' "$CHANGED_FILES" | awk 'NF{c++}END{print c+0}')"
STREAM_NOTE="${STREAM_SLUG:+ — stream: $STREAM_SLUG}"
LOG_LINE="${TODAY} — session end (${SESSION_ID:0:12}) — ${FILE_COUNT} file(s) changed${STREAM_NOTE}"

if [[ -f "$LOG" ]]; then
  printf '%s\n' "$LOG_LINE" >> "$LOG" 2>/dev/null || true
else
  { printf '# Memory log\n\n'; printf '%s\n' "$LOG_LINE"; } > "$LOG" 2>/dev/null || true
fi

# ── session-YYYYMMDD.md ──────────────────────────────────────────────────────

SESSION_FILE=".platform/memory/session-${TODAY}.md"
FILES_BLOCK="_(none recorded)_"
if [[ -n "$CHANGED_FILES" ]]; then
  FILES_BLOCK="$(printf '%s\n' "$CHANGED_FILES" | awk 'NF{print "- " $0}')"
fi

# Write header only when creating a new file (check before >> creates it)
IS_NEW=0; [[ ! -f "$SESSION_FILE" ]] && IS_NEW=1

{
  if (( IS_NEW )); then
    printf '# Session notes — %s\n\n' "$TODAY"
    printf '_Auto-generated by memory-persist.sh. Edit freely._\n\n---\n\n'
  fi
  printf '## Turn ended %s\n\n' "$NOW"
  [[ -n "$STREAM_SLUG" ]] && printf '**Stream:** %s\n\n' "$STREAM_SLUG"
  printf '**Files changed:**\n\n%s\n\n' "$FILES_BLOCK"
  printf '**Learnings / decisions / next steps:** _fill in or let the agent reflect_\n\n---\n\n'
} >> "$SESSION_FILE" 2>/dev/null || true

exit 0
